#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase && rm -f *.png 0/Ma 0/wallShearStress 0/Cf

#------------------------------------------------------------------------------
